trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  versionBase: 1.0.0
  branchType: master
  buildVersion: $(versionBase).$(Build.BuildId)-$(branchType)

steps:
- script: npm ci
  displayName: 'npm install'

- script: CI=true npm test
  displayName: 'npm test'

- script: npm run build
  displayName: 'npm build'

# Archive build artifact
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveFile: '$(System.DefaultWorkingDirectory)/$(buildVersion).zip'

# Publish build artifact (To Azure Devops)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/$(buildVersion).zip'
    artifactName: 'release-files'
