trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest
  demands:
  - npm

variables:
  versionBase: 1.0.0
  branchType: master
  buildVersion: $(versionBase).$(Build.BuildId)-$(branchType)

jobs:
  - job: Build
    displayName: Build+Test+Package
    steps:
    - template: azure-pipeline-files/build-test.yml
    - template: azure-pipeline-files/package.yml